Fix escaping special html entites in search output
JuliaDocs/Documenter.jl pull request #2461
Opened 2024-02-20 18:59 UTC by Hetarth02

This PR aims to close Issue #2441 and Issue #2428.

2024-02-21 03:10 UTC, mortenpi requested changes
I can confirm that it fixes #2441, but not #2428:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/9eb0490f-1c52-4687-bef6-4f63ec09690f)

To repro, I just added a 

```
### &harr; &harr; &harr;
```

heading into the Markdown source.

2024-02-21 03:10 UTC, mortenpi commented on assets/html/js/search.js
> +      "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js",
Hmm. This now duplicates the dependency.. so let's not include `lodash` here (see also https://github.com/JuliaDocs/Documenter.jl/pull/2415#discussion_r1477029876). The implementation is trivial, so let's just remove the comments, and put the implementation here (with appropriate attribution; lodash is MIT).

https://github.com/lodash/lodash/blob/main/src/escape.ts

2024-02-24 09:59 UTC, Hetarth02 commented
> I can confirm that it fixes #2441, but not #2428:
> 
> ![image](https://private-user-images.githubusercontent.com/147757/306480775-9eb0490f-1c52-4687-bef6-4f63ec09690f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NjgwNTIsIm5iZiI6MTcwODc2Nzc1MiwicGF0aCI6Ii8xNDc3NTcvMzA2NDgwNzc1LTllYjA0OTBmLTFjNTItNDY4Ny1iZWY2LTRmNjNlYzA5NjkwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwOTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWIxM2RmYTBiYjAxZGNlNWY5YTJkNTc3ZDIxMTU4MmYyZmJjYWI1MTAzMzIxYzRmZjhhMDBmMDQ1YzNmNmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6-32Dc_7OmUsNl8ZqDpJxchNHkBfqszV3lKNqw4WLUI)
> 
> To repro, I just added a
> 
> ```
> ### &harr; &harr; &harr;
> ```
> 
> heading into the Markdown source.

## Case 1

I looked into this a little bit and I found out that, when enter into `.md` files and render

```md
### ↔ ↔ ↔
```

I cannot find it in the search using `harr` or `↔`.
But it renders in html as the symbol.

> For ref, see below images.

### HTML Renders
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/56b1a515-9bf7-411a-87fc-71b782990582)

![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/7f968e73-20dd-44ff-b354-1f563118f32c)

### Search
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/295bfc07-1ca0-45f4-b668-16a9a324b146)

![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/ced09953-e013-4be7-a9c5-fdb6bd5e384c)

## Case 2

But when I enter below into `.md` files and render

```md
### &harr; &harr; &harr;
```

I can find it in the search using `harr` but not using `↔`.
Also it does not renders in html as the symbol.

> For ref, see below images.

### HTML Renders
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/97d57136-7b3f-441e-b192-8b74299432b0)

![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/b41a2c1a-a6df-4e36-9a7d-920cff62bbc2)

### Search
![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/4a577037-c1a7-4cb8-896b-cd28c0a1422e)

![image](https://github.com/JuliaDocs/Documenter.jl/assets/80420115/6474e178-7a15-4f2d-ac67-2ec339d690d9)

2024-02-27 12:42 UTC, mortenpi approved these changes

2024-02-27 12:48 UTC, merged