Make `_any_color_fmt` a method which can be overridden.
JuliaDocs/Documenter.jl pull request #2490
Opened 2024-04-03 22:28 UTC by asinghvi17

This has uses for DocumenterMarkdown as well as DocumenterVitepress, and will allow us to get rid of the current `@ansi` block formulation.

The PR simply changes the check in `_any_color_fmt` to calling a function instead of a hardcoded type check; that function can then be extended.

2024-04-04 03:05 UTC, goerz approved these changes
Seems okay to me. Of course, there is still the fact that this is 100% internal. If we had an official stable plugin API it would be worth thinking about whether a function like this would be part of that plugin API. If it was, the function would have to have a non-underscore name (`format_supports_color`?) and a docstring that describes exactly what that a writer promises when it claims `format_supports_color` as `true`.

2024-04-04 03:36 UTC, mortenpi commented
I agree with Michael. I'm fine with this change as well, but in the current form, it would not have any guarantees of a public API. But I feel this could be turned into a public API as well, if we can articulate a precise docstring for it.

2024-04-04 10:53 UTC, asinghvi17 commented
Thanks for the feedback!  

I would love to make this a public API - if so, it would probably go in `Documenter.Writers`, and perhaps the name `supports_ansicolor` would work?  That would also remove the need for all writers to have an `ansicolor` field if they do support it.

Perhaps a docstring like:

```julia
"""
	supports_ansicolor(writer::Documenter.Writer)::Bool

Returns `true` if the writer `writer` accepts ANSI colored input from Documenter, or `false` if it does not. 

Defaults to `false`.

This is mainly used to color the output of `@example` and `@repl` blocks.
"""
```

2024-04-14 02:54 UTC, mortenpi commented
> it would probably go in `Documenter.Writers`

We're moving away from the submodules. `Documenter.writer_supports_ansicolor` would probably be a good name.

Re the docstring: generally, looks fine. Though I think the main difference will be that the `show` and other IO methods will be called with an `color=true` IOContext?

2025-03-27 14:33 UTC, fingolfin commented
@asinghvi17 are you still interested in working on this?

2025-04-30 20:09 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +    idx = findfirst(_is_color_fmt, doc.user.format)
```suggestion
    idx = findfirst(writer_supports_ansicolor, doc.user.format)
```

2025-04-30 20:09 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +_is_color_fmt(::Documenter.HTMLWriter.HTML) = true
```suggestion
# General fallback.
""'
	writer_supports_ansicolor(::Documenter.Writer)::Bool
	
Returns whether the writer supports ANSI-colored output (`true`) or not (`false`).

This is usually relevant in Documenter blocks that execute code, like `@example` or `@repl`.
"""
writer_supports_ansicolor(::Documenter.Writer) = false
# HTML accepts ANSI, so this is `true`.
writer_supports_ansicolor(::Documenter.HTMLWriter.HTML) = true
```

2025-04-30 20:12 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +""'
```suggestion
"""
```

2025-04-30 20:13 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +	writer_supports_ansicolor(::Documenter.Writer)::Bool
```suggestion
    writer_supports_ansicolor(::Documenter.Writer)::Bool
```

2025-04-30 20:16 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +This is usually relevant in Documenter blocks that execute code, like `@example` or `@repl`.
```suggestion
This is usually relevant in Documenter blocks that execute code, like `@example` or `@repl`.

If `true`, these blocks will call `show` on the returned Julia object with `color = true`.  If `false`, then show is called with `color=false`.  
```

2025-04-30 20:21 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +writer_supports_ansicolor(::Documenter.HTMLWriter.HTML) = true
```suggestion
writer_supports_ansicolor(::Documenter.HTML) = true
```

2025-04-30 22:33 UTC, asinghvi17 reviewed
Let's see if this works instead

2025-04-30 22:33 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +writer_supports_ansicolor(::Documenter.Writer) = false
```suggestion
writer_supports_ansicolor(::Writer) = false
```

2025-04-30 22:33 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +writer_supports_ansicolor(::Documenter.HTML) = true
```suggestion
writer_supports_ansicolor(::HTMLWriter.HTML) = true
```

2025-04-30 22:33 UTC, asinghvi17 reviewed
Let's see if this works instead

2025-04-30 22:40 UTC, asinghvi17 commented
Maybe using `HTML` is messing something up here?  But I have no clue what.

2025-05-02 15:21 UTC, goerz requested changes
LGTM, apart from the trailing whitespace, which should be trivial to fix ;-)

2025-05-02 15:21 UTC, goerz commented on src/expander_pipeline.jl
> +
There's some trailing whitespace in this line (the GitHub UI doesn't show it)

@mortenpi Don't we have automatic code formatting in place at this point? Source code formatting, including preventing trailing white space should be be flagged by CI

2025-05-02 15:31 UTC, asinghvi17 commented on src/expander_pipeline.jl
> +
There is a Runic run that seems to have passed, maybe Runic doesn't pick this up?

https://github.com/JuliaDocs/Documenter.jl/actions/runs/14786412938/job/41515527745?pr=2490

2025-05-02 15:33 UTC, asinghvi17 commented
@lazarusA after this PR is released,  we can deprecate the `@ansi` block in Vitepress

2025-05-02 16:45 UTC, goerz commented on src/expander_pipeline.jl
> +
Well, now I think you deleted the blank line that makes the signature a code block.

There is also more trailing whitespace in the last line of that docstring.

Independent of `runic` picking this up: I would recommend setting up your text editor to remove trailing spaces from `.jl` files automatically, on save.

We should probably also have a `make codestyle` or something that people can use to easily ensure that all code is properly formatted when preparing PRs.

2025-05-02 16:46 UTC, goerz commented on src/expander_pipeline.jl
> +
I think I was able to push a fix-commit to this PR…

2025-05-05 03:42 UTC, mortenpi approved these changes
LGTM as well, thank you! I took the liberty of putting the new function into the manual as well, under the public API section.

2025-05-05 03:49 UTC, merged